CREATE TABLE IF NOT EXISTS settings (
	id VARCHAR PRIMARY KEY,
	user_email VARCHAR unique not null,
	aws_access_key VARCHAR,
	aws_secret VARCHAR,
	aws_region VARCHAR,
	no_sql_provider VARCHAR,
	document_table_name VARCHAR,
	parsing_api_key VARCHAR,
	buckets_list VARCHAR,
	scan_bucket VARCHAR,
	elastic_search_index VARCHAR,
	elastic_search_host VARCHAR,
	elastic_search_port VARCHAR,
	elastic_search_api_key VARCHAR,
	search_document_db BOOLEAN,
	search_elastic_search BOOLEAN,
	store_logs_in_db BOOLEAN,
	mongo_db_host VARCHAR,
	mongo_db_database VARCHAR,
	mongo_db_username VARCHAR,
	mongo_db_password VARCHAR,
	openai_api_key VARCHAR,
	hugging_face_api_key VARCHAR,
	qdrant_api_key VARCHAR,
	qdrant_host VARCHAR,
	qdrant_port VARCHAR,
	qdrant_collection_name VARCHAR,
	cloud_provider VARCHAR,
	azure_blob_connection_string VARCHAR,
	azure_blob_container_name VARCHAR,
	cosmos_db_host VARCHAR,
	cosmos_db_container VARCHAR,
	cosmos_db_key VARCHAR,
	gcp_key_file_content VARCHAR
)
