version: '3'

services:
  app:
    build: ./app/
    ports:
      - "8000:8000"
  frontend:
    build: ./frontend/
    ports:
      - "8080:8080"
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'

