version: '3'

services:
  app:
    build: ./app/
    ports:
      - "8000:8000"
    depends_on:
      - "sqs"
      - "parse-engine"
      - "db"

  db:
    image: postgres:12-bullseye
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: heissdocs
    ports:
      - '5432:5432'

  sqs:
    image: softwaremill/elasticmq
    ports:
      - "9324:9324"
      - "9325:9325"

  parse-engine:
    build: ./engine/
    depends_on:
      - "sqs"

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data
    volumes:
      - minio_data:/data

  # qdrant:
  #   image: qdrant/qdrant
  #   ports:
  #     - "6333:6333"
  #   extra_hosts:
  #     - "host.docker.internal:host-gateway"

volumes:
  minio_data:
  esdata: